In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/SMuralidhar/Documents/Python Scripts/heart.csv")

In [3]:
df.head(4)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1

In [5]:
df.describe().T

              count        mean         std   min     25%    50%    75%    max
Age           918.0   53.510893    9.432617  28.0   47.00   54.0   60.0   77.0
RestingBP     918.0  132.396514   18.514154   0.0  120.00  130.0  140.0  200.0
Cholesterol   918.0  198.799564  109.384145   0.0  173.25  223.0  267.0  603.0
FastingBS     918.0    0.233115    0.423046   0.0    0.00    0.0    0.0    1.0
MaxHR         918.0  136.809368   25.460334  60.0  120.00  138.0  156.0  202.0
Oldpeak       918.0    0.887364    1.066570  -2.6    0.00    0.6    1.5    6.2
HeartDisease  918.0    0.553377    0.497414   0.0    0.00    1.0    1.0    1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [9]:
df.select_dtypes(include='number').columns

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease'],
      dtype='object')

In [12]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [15]:
df['zscore_RBP']=(df.RestingBP-df.RestingBP.mean())/df.RestingBP.std()
df['zscore_Cholesterol']=(df.Cholesterol-df.Cholesterol.mean())/df.Cholesterol.std()
df['zscore_MaxHR']=(df.MaxHR-df.MaxHR.mean())/df.MaxHR.std()
df['zscore_Oldpeak']=(df.Oldpeak-df.Oldpeak.mean())/df.Oldpeak.std()

In [16]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore_RBP,zscore_Cholesterol,zscore_MaxHR,zscore_Oldpeak
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979

In [21]:
df_outliers = df[(df['zscore_RBP'] > 3) | (df['zscore_RBP'] < -3) |
                 (df['zscore_Cholesterol'] > 3) | (df['zscore_Cholesterol'] < -3) |
                 (df['zscore_MaxHR'] > 3) | (df['zscore_MaxHR'] < -3) |
                 (df['zscore_Oldpeak'] > 3) | (df['zscore_Oldpeak'] < -3)]

In [25]:
df_outliers.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore_RBP,zscore_Cholesterol,zscore_MaxHR,zscore_Oldpeak
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1,-0.777595,3.018723,-0.267450,-0.831979
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0,3.111322,0.385800,-1.210093,-0.831979
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1,-0.129442,3.695238,-0.463834,0.105606
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1,0.410685,0.294379,0.125318,3.855945
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1,3.651449,-0.007310,0.203871,1.043191

In [26]:
df_no_outliers = df[(df['zscore_RBP'] < 3) & (df['zscore_RBP'] > -3) &
                 (df['zscore_Cholesterol'] < 3) & (df['zscore_Cholesterol'] > -3) &
                 (df['zscore_MaxHR'] < 3) & (df['zscore_MaxHR'] > -3) &
                 (df['zscore_Oldpeak'] < 3) & (df['zscore_Oldpeak'] > -3)]

In [28]:
df_no_outliers.shape

(899, 16)

In [29]:
df_outliers.shape

(19, 16)

In [30]:
df.shape

(918, 16)

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [33]:
df_no_outliers.select_dtypes(include='object').columns

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

In [39]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply label encoding to each categorical column
df_no_outliers['ChestPainType_le'] = le.fit_transform(df_no_outliers['ChestPainType'])
df_no_outliers['RestingECG_le'] = le.fit_transform(df_no_outliers['RestingECG'])
df_no_outliers['ExerciseAngina_le'] = le.fit_transform(df_no_outliers['ExerciseAngina'])
df_no_outliers['ST_Slope_le'] = le.fit_transform(df_no_outliers['ST_Slope'])

C:\Users\SMuralidhar\AppData\Local\Temp\ipykernel_33516\3140489688.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ChestPainType_le'] = le.fit_transform(df_no_outliers['ChestPainType'])
C:\Users\SMuralidhar\AppData\Local\Temp\ipykernel_33516\3140489688.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['RestingECG_le'] = le.fit_transform(df_no_outliers['RestingECG'])
C:\Users\SMuralidhar\AppData\Local\Temp\ipykernel_33516\3140489688.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ExerciseAngina_le'] = le.fit_transform(df_no_outliers['ExerciseAngina'])
C:\Users\SMuralidhar\AppData\Local\Temp\ipykernel_33516\3140489688.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ST_Slope_le'] = le.fit_transform(df_no_outliers['ST_Slope'])

In [40]:
df_no_outliers

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore_RBP,zscore_Cholesterol,zscore_MaxHR,zscore_Oldpeak,ChestPainType_le,RestingECG_le,ExerciseAngina_le,ST_Slope_le
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979,1,1,0,2
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606,2,1,0,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979,1,2,0,2
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398,0,1,1,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979,2,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123,3,1,0,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810,0,1,0,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123,0,1,1,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979,1,0,0,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979,2,1,0,2

In [46]:
df_no_outliers_n=df_no_outliers.drop(['ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope','zscore_RBP', 'zscore_Cholesterol', 'zscore_MaxHR',
       'zscore_Oldpeak','Sex'],axis='columns')

In [42]:
df.select_dtypes(include='number').columns

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'zscore_RBP', 'zscore_Cholesterol', 'zscore_MaxHR',
       'zscore_Oldpeak'],
      dtype='object')

In [47]:
df_no_outliers_n.head(5)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,ChestPainType_le,RestingECG_le,ExerciseAngina_le,ST_Slope_le
0,40,140,289,0,172,0.0,0,1,1,0,2
1,49,160,180,0,156,1.0,1,2,1,0,1
2,37,130,283,0,98,0.0,0,1,2,0,2
3,48,138,214,0,108,1.5,1,0,1,1,1
4,54,150,195,0,122,0.0,0,2,1,0,2

In [48]:
x=df_no_outliers_n.drop('HeartDisease',axis='columns')
y=df_no_outliers_n['HeartDisease']

In [49]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2)
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
x_scaled=scale.fit_transform(x)

In [51]:
x_scaled

array([[0.24489796, 0.57142857, 0.55791506, ..., 0.5       , 0.        ,
        1.        ],
       [0.42857143, 0.76190476, 0.34749035, ..., 0.5       , 0.        ,
        0.5       ],
       [0.18367347, 0.47619048, 0.54633205, ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.59183673, 0.47619048, 0.25289575, ..., 0.5       , 1.        ,
        0.5       ],
       [0.59183673, 0.47619048, 0.45559846, ..., 0.        , 0.        ,
        0.5       ],
       [0.20408163, 0.55238095, 0.33783784, ..., 0.5       , 0.        ,
        1.        ]])

In [53]:
from sklearn.svm import SVC
svm=SVC()
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x_scaled,y,test_size=.2)

In [54]:
svm.fit(xtrain,ytrain)

SVC()

In [55]:
svm.score(xtest,ytest)

0.8333333333333334

In [56]:
from sklearn.ensemble import BaggingClassifier
bag=BaggingClassifier(base_estimator=svm,n_estimators=20,max_samples=0.8,oob_score=True,random_state=10)
bag.fit(xtrain,ytrain)
bag.score(xtest,ytest)

C:\Users\SMuralidhar\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

0.8611111111111112